name: pycalculix-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.23
  - gmsh
  - calculix
  - matplotlib
  - pip:
      - git+https://github.com/spacether/pycalculix.git
